### ISSUE TITLE
Add CocoaPods support

### ISSUE THREAD

**Issue by arnaudmeunier** [p2/OAuth2#10]
CocoaPods recently added support for Swift. Could we add an Oauth2.podspec file to make this great lib available through CocoaPods?

**Comment by p2** [comment]
I haven't used CocoaPods personally, but I'd be happy to accept a pull request to enable it.

**Comment by arnaudmeunier** [comment]
I'm also brand new to it. Gave it a shot last night, as I realized they added Swift support. Makes dependencies management much easier (tried with Alamofire and SwiftyJSON). Seems to be pretty straightforward to add a new pod, according to this piece of documentation: http://guides.cocoapods.org/making/specs-and-specs-repo.html

There might be CocoaPods users who could help us with this? Otherwise I'll give it a try! :)

**Comment by damienrambout** [comment]
@arnaudmeunier I think you have to be the one that pushes the spec file to the Cocoapods repo so that you are the only one able to push updates for your framework.

However, I'll pull request a Podspec file that should be ready to push. Should not be difficult since your project's structure is really flat. I'll do that next week I guess.

Just tell me how you want to call you framework (module)? `OAuth2` seems to generic to me and could lead to future conflicts on Cocoapods repo. Maybe `P2OAuth2`?

Then all you'll have to do is :
1. Register your email with Cocoapods. Somethink like `pod trunk add-owner P2OAuth2 <your-email-address>`
2. `pod spec lint P2OAuth2.podspec` to check that your release is valid and ready to push.
3. `pod trunk push P2OAuth2.podspec` to push your release to the main repo.

Note that you have to edit (`spec.version`) and push your podspec everything you release a new version of your framework. Ideally, pod versions should be based on the tags your create. You'll probably have to create 3 different versions to support Swift 1.0, 1.1 and 1.2. I'd suggest you to use `X.Y.Z` tag names because, but that's not mandatory (it's just easier than remembering the mappings between your pod versions and tags).

**Comment by damienrambout** [comment]
Sorry, my message was meant for @p2.

**Comment by paul999** [comment]
+1, this would really make it easier to use this framework

**Comment by p2** [comment]
Thanks @damienrambout , I finally got to it and managed to get it up as **p2.OAuth2**.
