### ISSUE TITLE
Best practice for usage?  (appdelegate vs. singleton) 

### ISSUE THREAD

**Issue by sigursalt** [p2/OAuth2#120]
Hi,

First off - awesome library.  My work has an old objC library they reference in their SSO integration documents and I decided to try your library instead.  So glad I did.

Quick question... is there a best practice for _where_ to implement in an Xcode project?  

I started my implementation by just creating an initial VC with all the settings and calls until I got it running, then I moved `var oauth2: OAuth2CodeGrant!` into the AppDelegate so I always have a reference to it.  Is that considered 'clean' enough?

It runs fine.  It is throwing an error when I try to use `applicationDidBecomeActive` in AppDelegate to run `authorize()` - I get an "Attempt to present UserViewController on ViewController whose view is not in the window hierarchy!" error.

It seems like there's so many different ways to integrate it into a project - just wondering what's considered the 'cleanest'?

Thanks again for the library.

**Comment by p2** [comment]
Glad to hear you like it!

First, you'll get the error in `applicationDidBecomeActive` because it's too early to show UI at this point. Still, you can hold on to an instance in App Delegate, but let a view controller take care of when to call `authorize()`.

Best practice really depends on your use case. If there's only ever one view controller where you'll need an OAuth2 token, it's fine to let it live in there. What I usually do is create some _Loader_ or _Server_ class which holds on to an OAuth2 instance, then let that class live where I need it (often app delegate). The [`DataLoader`](https://github.com/p2/OAuth2App/blob/master/OAuth2App/DataLoader.swift) implementation of the OAuth2 sample app might give you ideas on how to package it.

I'm considering adding such a loader class to the Swift 3 version of the library so it can be readily used. This library is still very “developer-focused” for integration into loader frameworks and such, so I haven't taken enough care of making it easy to use out of the box.

**Comment by p2** [comment]
The `develop` branch now has an early implementation of `OAuth2DataLoader`, for which I have yet to write a description, but it does exactly that, attempts to load, queues all calls on 401 and resumes them after a successful authorization.

**Comment by p2** [comment]
Version 3 now has an `OAuth2DataLoader` that you can use. It takes care of authorization, all you need to do is configure your OAuth2 handle and start requesting data. Updated instructions: https://github.com/p2/OAuth2/#usage

Alternatively you can now use Alamofire version 4 and integrate it with OAuth2 for the same effect: https://github.com/p2/OAuth2/wiki/Alamofire-4
