### ISSUE TITLE
OAuth2CodeGrantFacebook and redirect URIs callback

### ISSUE THREAD

**Issue by aliasdoc** [p2/OAuth2#168]
Hi,

I'm trying to use this library to make social login with my API but I have a problem with callback URIs, as you know Facebook don't accept custom uris (xyz://xxx/xxx) for callback and I use a small script in my server to receive callback and transmit to my app by calling my custom scheme registered in my app, but when this library handle url it says:
```
[Debug] OAuth2: Invalid redirect URL: Expecting «https://xxx/callback/facebook» but received «oauth-swift://oauth-callback/facebook?...........»

```

Here is my code:

```

var oauth2 = OAuth2CodeGrantFacebook(settings: [
        "client_id": "xxxxxx",
        "client_secret": "xxxxxx",
        "authorize_uri": "https://www.facebook.com/dialog/oauth",
        "token_uri": "https://graph.facebook.com/oauth/access_token",
        "scope": "email",
        "redirect_uris": ["https://xxx/callback/facebook"],
        "verbose": true,
        ] as OAuth2JSON)

oauth2.authConfig.authorizeEmbedded = false		// the default
        oauth2.useKeychain = false
        
        oauth2.authorize() { authParameters, error in
            if let params = authParameters {
                print("Authorized! Access token is in `oauth2.accessToken`")
                print("Authorized! Additional parameters: \(params)")
            }
            else {
                print("Authorization was cancelled or went wrong: \(error)")   // error will not be nil
            }
        }     

```

Thank you for your help.

**Comment by p2** [comment]
I see. This of course is a use-case that's not covered by OAuth2 specifically, but I can see how this is used as a last resort for endpoints who do not allow custom callback URIs. Since you have a server, have you looked at [**Universal Links**](https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html)? That may be a better solution.

If universal links are not an option, I think you should subclass `OAuth2FacebookGrant` and override `open func validateRedirectURL(_ redirect: URL) throws -> String`, bypassing the callback URI check. I don't think that's good practice but if you must make this work, this would be the way. In the override, call `super` in a `do {  }` block and catch `invalidRedirectURL`. You will then need to extract `code` manually; maybe it's easier to copy/paste the original method and not throw `invalidRedirectURL`.

**Comment by aliasdoc** [comment]
Hi @p2 , thanks for your help but If I need to subclass, how OAuth2FacebookGrant is supposed to work ?? 
I try with Universal Links.

**Comment by p2** [comment]
Try universal links. If that doesn't work, try to subclass – the class will still work as usual, but will not complain about the redirect URL mismatch.

**Comment by aliasdoc** [comment]
ok, thanks you @p2.
