### ISSUE TITLE
finalParams removing client_id and client_secret but those required for my flow

### ISSUE THREAD

**Issue by bleeckerj** [p2/OAuth2#217]
I'm trying to understand how I should either extend a class here or how to use the framework in a specific case. I'm running an authorize flow against [Strava's API.](https://strava.github.io/api/v3/oauth/) 

Strava specifically requires client_id and client_secret in the params for the token request. Everything works fine — except that `OAuth2AuthRequest` formally removes these from the request for the token after authorization. If I comment out the lines in `OAuth2AuthRequest` (206 & 207)
```
//				finalParams.removeValue(forKey: "client_id")
//				finalParams.removeValue(forKey: "client_secret")
```

The flow works just fine. But — what's the right way to do this? (I've been using OAuth2 for about 3 hours, btw, so please forgive me if I've overlooked a key aspect of configuration. It works for my requests — but only if I comment out those lines. I'm using `OAuth2CodeGrant` as my authorization handler.

**Comment by p2** [comment]
You need to tell the client to put client_id and client_secret in the request body instead of the header.

See [the wiki](https://github.com/p2/OAuth2/wiki), the [short code grant flow description](https://github.com/p2/OAuth2#code-grant) and [advanced settings](https://github.com/p2/OAuth2#advanced-settings) in the README (and lines 192 & 193 in the file where you uncommented the code ;) ).

**Comment by bleeckerj** [comment]
Thank you Pascal. I was confused as to the semantics of "in the body" versus as a url parameter. My misunderstanding. Thanks for responding so quickly..if I had scrolled up I can see now that I would've seen those two lines.
