### ISSUE TITLE
Access token response parsing with empty `error_description` string.

### ISSUE THREAD

**Issue by markst** [p2/OAuth2#247]
Apologies if this a server side issue we need to resolve. 

Our OAuth server returns the following response when using invalid credentials:
```json
{"error_description":"","error":"access_denied"}
```

`OAuth2Base.assureNoErrorInResponse` will check for presence of `error_description` and throws a `OAuth2Error`. This then results in being unable to present an appropriate error message. 

If I change the order of `assureNoErrorInResponse` error checks so that presence of `params["error"]` has precedence over `error_description`. I can display the appropriate error.

Is there any way of getting additional data from the `OAuth2Error` which I might be able to retrieve the `access_denied` error state?

**Comment by p2** [comment]
Yes, so if `error_description` is present it's preferred.

If you control the server you can remove it if it's empty (since it's useless) or you could create a pull request so that OAuth2 only prefers `error_description` if it's actually longer than 0 characters, something like: `if let err_msg = params["error_description"] as? String, err_msg.count > 0 {` in `OAuth2Base.assureNoErrorInResponse`.

**Comment by markst** [comment]
thanks p2
