### ISSUE TITLE
Cocoapods not working for Version 5

### ISSUE THREAD

**Issue by muzoman** [p2/OAuth2#320]
if your podfile has:

pod 'p2.OAuth2'

it pulls in version 4.2.0 - not the latest 5.0.0, if you do this:

pod 'p2.OAuth2', '5.0.0'

It causes an error:

"CocoaPods could not find compatible versions for pod "p2.OAuth2"

**Comment by muzoman** [comment]
If you do this:

pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2', :submodules => true

it does pull in version 5.0.0 though.

**Comment by djbe** [comment]
I've published version 5.0.0 to CocoaPods, but seems like someone forgot to update the Swift version in the `.swift-version` file to 5.0. This should be addressed before the next release to avoid any potential issues.

**Comment by ossus-lib** [comment]
Cocoapods support is now removed with version 5.1, you can use Swift Package Manager starting with that version.

**Comment by djbe** [comment]
@ossus-lib And how are all CocoaPods users supposed to use the latest version then? SPM is still way too limited and unsupported by too many libraries to "just switch".

**Comment by ossus-lib** [comment]
You can use SPM for OAuth2 and CocoaPods for other libraries, not?

And one can still do this, right?

    pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2', :submodules => true

**Comment by djbe** [comment]
Maybe, no idea (haven't tried it yet). Thing is that quite a few people probably have build processes / flows dependent on CocoaPods, and won't switch to SPM for quite a while yet. 

The latter cannot be used in podspecs of other libraries, and ignores any versioning.

Dropping CocoaPods is your prerogative, it's your library. But if you're dropping support just because you don't use it yourself, and you need help with maintaining CocoaPods support, I (and other users) can do that.

**Comment by ossus-lib** [comment]
I thought the update to 5.1 broke something needed for Cocoapods, maybe it did not? Also, I think you actually updated the last few versions with Cocoapods, if it's ok for you can you submit a PR to re-enable Cocoapods if it's just the podfile?
