### ISSUE TITLE
"Back" is the rewind button

### ISSUE THREAD

**Issue by nickvelloff** [p2/OAuth2#40]
Any chance we can use a proper back button for back?
<img width="393" alt="screenshot 2015-08-05 21 56 04" src="https://cloud.githubusercontent.com/assets/885369/9104142/0e3a2918-3bbd-11e5-9196-ad8599097d40.png">

**Comment by p2** [comment]
The reason I haven't changed it yet is that I didn't want to use a normal "< Back" button because it conflicts with UI expectations (especially if the login is not shown modally but pushed) and there is no better symbol provided by UIKit. This one doesn't require an image to be embedded, but I am open to better solutions of course.

**Comment by nickvelloff** [comment]
Makes sense. Would it make any sense to allow us to define the back button
text or image perhaps? I'm getting user feedback about rewind being a bit
confusing.
BTW i'm using this on the iOS app for http://thegrid.io - and we are close
to dropping 50k+ founding members on it. Really appreciate the work you put
into this.

**Comment by p2** [comment]
Good idea, implemented. 2 ways to customize the back button:

```swift
oauth2.authConfig.ui.backButton = UIBarButtonItem(...)
oauth2.authorize()
```

or

```swift
let vc = <# presenting view controller #>
let web = oauth2.authorizeEmbeddedFrom(vc, params: nil)
web.backButton = UIBarButtonItem(...)
oauth2.afterAuthorizeOrFailure = { wasFailure, error in
    web.dismissViewControllerAnimated(true, completion: nil)
}
```

**Comment by nickvelloff** [comment]
Thanks so much for adding this. I’m going to try it now!

**Comment by nickvelloff** [comment]
Worked great. Thanks again.
