### ISSUE TITLE
PasswordGrant Questions

### ISSUE THREAD

**Issue by whitefoxy** [p2/OAuth2#61]
I am implemeting your  framework in my App and I have some questions:

1. Why it don't support "client_id & client_secret" in body?
2. On authorization I receive this warning: "WARNING: expecting “bearer” token type but got “Bearer”", why? There are no difference between "Bearer" and "bearer", but it is not nice to see a useless warning when debug. Many OAuth providers use both variants.

3. What mean "params" array and "autoDismiss" boolean? There are information in Docs. If they are useless, then why there are required? `oauth2.authorize(params: nil, autoDismiss: true);`

4. Why it use for requesting "access_token" the "authorize_uri"? In Password Grant it must request directly the "token_uri".

5. `parameters` in `oauth2.onAuthorize` returns empty string.

```
oauth2.onAuthorize = { parameters in
    print("Did authorize with parameters: \(parameters)")
}

Console: Did authorize with parameters: [:]
```

**Comment by p2** [comment]
1. The secret in the body is [currently supported for the Code Grant flow](http://p2.github.io/OAuth2/Classes/OAuth2CodeGrant.html#/s:vC6OAuth215OAuth2CodeGrant12secretInBodySb) only. It will be available for all grants soon.

2. This is an oversight because nobody has run into the issue yet. Officially it's lowercase "bearer" but agreed, doesn't make sense to be case-sensitive.

3. Both should be optional and not required, this is an error in the class override. `params` allows you to specify additional parameters during authorization, `autoDismiss` is used when using the built-in view controller. Agreed, must be better documented.

4. See #47 

5. Yes, that's wrong

Pull requests are always welcome!
