### ISSUE TITLE
Prerequisites for SafariViewConroller

### ISSUE THREAD

**Issue by 1b0t** [p2/OAuth2#99]
Hi,

I can not get the OAuth2 to use the SafariViewController on iOS 9.

I'm using `ImplicitGrant` and I've set `.authConfig.authorizeEmbedded = true`.

Maybe somebody can give me hint? What am I missing here? 🙈

Thanks!
Tobi

EDIT:

I figured out that one has to call `authorizeEmbeddedWith` instead of `authorizeEmbeddedFrom`. If this is always the case the docs should be updated to avoid confusion.

**Comment by p2** [comment]
Using `authorizeEmbeddedFrom()` is correct. What happens when you use it, does it not show anything or does it not use the Safari view controller but a different view controller?

**Comment by 1b0t** [comment]
`authorizeEmbeddedWith` works for me without any problem. iOS8 -> WebView. iOS9 -> SF. Is there any downside to using `authorizeEmbeddedWith`?

**Comment by p2** [comment]
There's not really a problem when you use `authorizeEmbeddedWith()`, but this bypasses several checks that make working with the library easier and requires that you supply the auth configuration by hand, which should not be necessary. `authorizeEmbeddedFrom()` should automatically supplies the configuration element, would not show the view when it's not necessary (e.g. when you have a refresh token), ensures the client is registered and _then_ calls `authorizeEmbeddedWith`.

When you set the following, does it then show Safari view when you use `authorizeEmbeddedFrom`? This is actually the default, so should not be necessary.

```swift
oauth2.authConfig.UI.useSafariView = true
```

If not, can you show me code how you instantiate OAuth2 and call the method?

**Comment by p2** [comment]
Ah I think I've found the problem, the renaming I did yesterday should fix it. The problem was that I was not careful when renaming some methods and there is a clash between two `authorizeEmbeddedFrom` methods, the one that is public and people should use and one that is OS-specific and may throw. You were involuntarily using the latter, which on iOS is the entry point to non-Safari-embedded auth.

I'll push a fix to CocoaPods as well. Thanks for reporting!!
